# Generated by Django 6.0.1 on 2026-02-02 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32767)),
                ('to_id', models.BigIntegerField()),
                ('op_desc', models.CharField(max_length=255, verbose_name='Opreration Description')),
                ('status', models.CharField(max_length=255)),
                ('op_args', models.CharField(blank=True, default='', max_length=1024, verbose_name='Operation Arguments')),
                ('op_add_txt', models.TextField(blank=True, default='', verbose_name='Operation Additional Text')),
                ('updt_dt', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('isrt_dt', models.DateTimeField(auto_now_add=True, verbose_name='Inserted Date')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acc_no', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=11)),
                ('acc_type', models.CharField(max_length=50, verbose_name='Account Type')),
                ('min_bal', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0, message='Minimum Balance cannot be < 0')], verbose_name='Minimum Balance')),
                ('dis_bal', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0, message='Desired Balance cannot be < 0')], verbose_name='Desired Balance')),
                ('def_parser', models.CharField(blank=True, default='', max_length=20, verbose_name='Default Parser')),
                ('def_grouper', models.CharField(blank=True, default='', max_length=40, verbose_name='Default Grouper')),
                ('act_ind', models.BooleanField(default=True)),
                ('isrt_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'acc_no'),
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_no', models.BigIntegerField()),
                ('exp_date', models.DateField(verbose_name='Expiry Date')),
                ('act_ind', models.BooleanField(default=True)),
                ('isrt_dt', models.DateTimeField(auto_now_add=True, verbose_name='Inserted Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(verbose_name='Transaction Date')),
                ('txn_desc', models.CharField(max_length=1024, verbose_name='Transaction Description')),
                ('grp_name', models.CharField(blank=True, default='', max_length=1024, verbose_name='Group Name')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount')),
                ('is_credit', models.BooleanField(default=False)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='moneyflow.creditcard')),
                ('src_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='moneyflow.fileaudit', verbose_name='Source File')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(verbose_name='Transaction Date')),
                ('txn_desc', models.CharField(max_length=1024, verbose_name='Transaction Description')),
                ('grp_name', models.CharField(blank=True, default='', max_length=1024, verbose_name='Group Name')),
                ('opr_dt', models.DateTimeField(verbose_name='Operation Date')),
                ('dbt_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0, message='Debit amount cannot be < 0')], verbose_name='Debit Amount')),
                ('cr_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0, message='Credit amount cannot be < 0')], verbose_name='Credit Amount')),
                ('ref_num', models.CharField()),
                ('cf_amt', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0, message='CF amount cannot be < 0')], verbose_name='CF Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='moneyflow.account')),
                ('src_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='moneyflow.fileaudit', verbose_name='Source File')),
            ],
        ),
    ]
