name: DEV
variables:
  - name: host
    value: localhost
  - name: port
    value: "8000"
  - name: baseurl
    value: http://{{host}}:{{port}}/moneyflow
  - secret: true
    name: jwt_access
  - secret: true
    name: jwt_refresh
